
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/db
      DATABASE_USER: app
      DATABASE_PASSWORD: app_password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app

volumes:
  db_data:

networks:
  app:
